language: node_js

node_js:
- '10.13.0'

before_script:
  - npm install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
- xvfb-run --server-args="-screen 0 1024x768x24" make test
- npm run tests
